kind: pipeline
name: build
type: docker

steps:
  - name: get commitID as tag
    image: alpine:latest
    commands:
      - apk add curl jq
      - echo "v$(expr $(curl https://r.regnault.dev/v2/estim-ai-back/tags/list | jq -r '.tags | length') + 1)" >> .tags

  - name: build backend
    image: plugins/docker
    environment:
      DJANGO_SUPERUSER_USERNAME:
        from_secret: DJANGO_SUPERUSER_USERNAME
      DJANGO_SUPERUSER_EMAIL:
        from_secret: DJANGO_SUPERUSER_EMAIL
      DJANGO_SUPERUSER_PASSWORD:
        from_secret: DJANGO_SUPERUSER_PASSWORD
      API_HOST:
        from_secret: API_HOST
    settings:
      registry: r.regnault.dev
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: r.regnault.dev/estim-ai-back
      context: back/
      dockerfile: back/Dockerfile
      build_args_from_env:
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - API_HOST

  - name: deploy estimai
    image: appleboy/drone-ssh
    settings:
      host:
        - 10.1.2.4
      username: stack-deployer
      password:
        from_secret: SSH_PASSWORD
      port: 22
      command_timeout: 2m
      script:
        - ./deploy.sh estimai

trigger:
  branch:
  - master
  event:
  - push