# Generated by Django 5.0.3 on 2024-04-01 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('name', models.TextField()),
                ('adress', models.TextField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('surface', models.IntegerField()),
                ('propertyType', models.IntegerField(default=1)),
                ('hasElevator', models.BooleanField()),
                ('hasGarden', models.BooleanField()),
                ('hasParkingSpace', models.BooleanField()),
                ('yearOfConstruction', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('isFurnished', models.BooleanField()),
                ('cityDepartmentCode', models.IntegerField()),
            ],
        ),
    ]
